# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from os import name
from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(826, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.treeWidget = QtWidgets.QTreeWidget(self.frame_2)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.gridLayout_2.addWidget(self.treeWidget, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listWidget = QtWidgets.QListWidget(self.frame_3)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.horizontalLayout.addWidget(self.listWidget)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.comboBoxGender = QtWidgets.QComboBox(self.frame_4)
        self.comboBoxGender.setObjectName("comboBoxGender")
        self.comboBoxGender.addItem("")
        self.comboBoxGender.addItem("")
        self.gridLayout_3.addWidget(self.comboBoxGender, 1, 3, 1, 1)
        self.lineEditName = QtWidgets.QLineEdit(self.frame_4)
        self.lineEditName.setObjectName("lineEditName")
        self.gridLayout_3.addWidget(self.lineEditName, 0, 2, 1, 3)
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.toolButtonPhotoBrowse = QtWidgets.QToolButton(self.frame_4)
        self.toolButtonPhotoBrowse.setObjectName("toolButtonPhotoBrowse")
        self.gridLayout_3.addWidget(self.toolButtonPhotoBrowse, 2, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(17, 37, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 6, 2, 1, 1)
        self.lineEditPhoto = QtWidgets.QLineEdit(self.frame_4)
        self.lineEditPhoto.setObjectName("lineEditPhoto")
        self.gridLayout_3.addWidget(self.lineEditPhoto, 2, 1, 1, 3)
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.pushButtonSubmit = QtWidgets.QPushButton(self.frame_4)
        self.pushButtonSubmit.setMaximumSize(QtCore.QSize(75, 16777215))
        self.pushButtonSubmit.setObjectName("pushButtonSubmit")
        self.gridLayout_3.addWidget(self.pushButtonSubmit, 3, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 3, 0, 1, 3)
        self.horizontalLayout.addWidget(self.frame_4)
        self.gridLayout_4.addWidget(self.frame_3, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 826, 22))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/close.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon)
        self.actionClose.setObjectName("actionClose")
        self.actionReload = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/reload.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReload.setIcon(icon1)
        self.actionReload.setObjectName("actionReload")
        self.menuMenu.addAction(self.actionClose)
        self.menuMenu.addAction(self.actionReload)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Qt Application"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "1"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "New Column"))
        self.treeWidget.headerItem().setText(2, _translate("MainWindow", "New Column"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "New Item"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "New Item"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "New Item"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("MainWindow", "New Item"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "java"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "QT "))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "C++"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "JavaScript"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.comboBoxGender.setItemText(0, _translate("MainWindow", "Male"))
        self.comboBoxGender.setItemText(1, _translate("MainWindow", "Female"))
        self.lineEditName.setPlaceholderText(_translate("MainWindow", "Type your name "))
        self.label_3.setText(_translate("MainWindow", "Photo :"))
        self.toolButtonPhotoBrowse.setText(_translate("MainWindow", "..."))
        self.label_2.setText(_translate("MainWindow", "Gender :"))
        self.label.setText(_translate("MainWindow", "Name :"))
        self.pushButtonSubmit.setText(_translate("MainWindow", "Submit"))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/tick.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonSubmit.setIcon(icon2)
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionReload.setText(_translate("MainWindow", "Reload"))
        self.populate_tree_widgets()
        self.populate_list_widget()
        self.pushButtonSubmit.clicked.connect(self.fill_form)
        self.toolButtonPhotoBrowse.clicked.connect(self.select_photo)
        
    def populate_tree_widgets(self):
        self.treeWidget.setHeaderLabels(["ID","NAME","COLOUR"])
        self.treeWidget.clear()
        x = ["apple","banana","mango","orange","pineapple","Watermelon"]
        for i , each in enumerate(x):
            item = QtWidgets.QTreeWidgetItem(self.treeWidget)
            item.setText(0,str(i))
            item.setText(1,each)
            
    def populate_list_widget(self):
        self.listWidget.clear()
        item = ["C++","HTML","Java","Python"]
        self.listWidget.addItems(item)
    def fill_form(self):
        name = self.lineEditName.text()
        if not name:
            QtWidgets.QMessageBox.about(self.centralwidget,"Name Required","Please fill the Name")
            return
        photo = self.lineEditPhoto.text()
        if not photo:
            QtWidgets.QMessageBox.about(self.centralwidget,"Photo Required","Please fill the Photo")
            return
        QtWidgets.QMessageBox.about(self.centralwidget,"Done","Submitted thank you")
    def select_photo(self):
        photo_path,ext = QtWidgets.QFileDialog.getOpenFileName(self.centralwidget,"Select Photo")
        if photo_path:
            self.lineEditPhoto.setText(photo_path)
import icons



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
